version: '3.8'

services:
  # NestJS Application
  app:
    build:
      context: .
      target: development
    container_name: nest-sample-app
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - SERVICE_PORT=3000
      - API_VERSION=1
    depends_on:
      - db
    networks:
      - nest-network
    restart: unless-stopped

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: nest-sample-db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nest_sample
      MYSQL_USER: nestuser
      MYSQL_PASSWORD: nestpassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - nest-network
    restart: unless-stopped

  # Production build
  app-prod:
    build:
      context: .
      target: production
    container_name: nest-sample-app-prod
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=production
      - SERVICE_PORT=3000
      - API_VERSION=1
    depends_on:
      - db
    networks:
      - nest-network
    restart: unless-stopped
    profiles:
      - production

volumes:
  mysql_data:

networks:
  nest-network:
    driver: bridge
